apiVersion: v1
kind: Service
metadata:
  name: account-service-c8a37fb6
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: account
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment-c81f31bf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - image: account:0.0.1
          name: account
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
