apiVersion: v1
kind: Service
metadata:
  name: account-service-c8a37fb6
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: account
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment-c81f31bf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.7
          name: hello-kubernetes
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
  namespace: argocd
spec:
  containers:
    - name: git
      command: ["sh"]
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 3000; rm -f /tmp/healthy; sleep 600
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      image: alpine/git
